version: '3'

services:
  
  node:
    image: nebulasio/go-nebulas
    build:
      context: ./docker
    ports:
      - '8680:8680'
      - '8684:8684'
      - '8685:8685'
      - '8888:8888'
      - '8086:8086'
    volumes:
      - .:/go/src/github.com/nebulasio/go-nebulas
    environment:
      - REGION=China
      - config=mainnet/conf/config.conf
    command: bash docker/scripts/neb.bash
